FROM node:8-alpine
MAINTAINER Boris Kolganov <b.kolganov@corp.mail.ru>

ENV SOLUTION_CODE_ENTRYPOINT=main.js
ENV SOLUTION_CODE_PATH=/opt/client/solution
ENV RUN_COMMAND='/usr/bin/node $SOLUTION_CODE_PATH/$SOLUTION_CODE_ENTRYPOINT'
